# Generated by Django 5.2.15 on 2026-07-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.FloatField(),
        ),
    ]
