# Generated by Django 5.2.15 on 2026-07-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_saleitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='weight_based',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
