# Generated by Django 5.2.15 on 2026-07-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_expensecategory_options_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reference',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
