# Generated by Django 5.2.15 on 2026-07-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_stock_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
