# Generated by Django 5.2.15 on 2026-07-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_sale_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
