# Generated by Django 5.2.17 on 2026-08-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0006_product_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="reference",
        ),
    ]
