# Generated by Django 5.2.17 on 2026-08-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_remove_stock_paid_remove_stock_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='reason',
            new_name='category',
        ),
    ]
