# Generated by Django 5.2.17 on 2026-08-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_rename_reason_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
