# Generated by Django 5.2.17 on 2026-08-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_expense_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='FirmExpense',
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'FirmExpense Category', 'verbose_name_plural': 'FirmExpense Categories'},
        ),
    ]
