# Generated by Django 5.2.17 on 2026-08-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_rename_expense_firmexpense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('note', models.CharField(max_length=200)),
            ],
        ),
    ]
